[package]
name = "corner"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdo = {path = "xdorust"}
anyhow = "1.0.56"
gdk = "0.15.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
